resolver: ghc-8.10.5
packages:
- .
extra-deps:
- hspec-2.9.2
- QuickCheck-2.14.2
- hspec-core-2.9.2
- hspec-discover-2.9.2
- hspec-expectations-0.8.2
- HUnit-1.6.2.0
- ansi-terminal-0.11.1
- call-stack-0.4.0
- clock-0.8.2
- quickcheck-io-0.2.0
- random-1.2.1
- setenv-0.1.1.3
- splitmix-0.1.0.4
- tf-random-0.5
- colour-2.3.6
- primitive-0.7.3.0
